### ISSUE TITLE
Unit tests | coverage

### ISSUE THREAD

**Issue by a-givertzman** [a-givertzman/hmi_networking#28]
#### Increase unit tests coverage
- [ ] Error: 27.53% < 30% | lib/src/core/ds_client_real.dart
- [x] ~Error: 0.00% < 30% | lib/src/core/stream_mearged.dart~ moved to hmi_core
- [x] ~Error: 0.00% < 30% | lib/src/core/stream_mearged_or.dart~ moved  to hmi_core
- [x] Error: 0.00% < 30% | lib/src/core/ds_data_stream_extract.dart -> #22 
- [x] Error: 0.00% < 30% | lib/src/core/ds_data_point_extracted.dart -> #22 
- [x] Error: 0.00% < 30% | lib/src/core/entities/double_container.dart -> #37 
- [ ] Error: 0.00% < 30% | lib/src/core/entities/network_operation_state.dart
- [ ] Error: 0.00% < 30% | lib/src/core/entities/data_object.dart
- [ ] Error: 0.00% < 30% | lib/src/core/entities/response.dart
- [ ] Error: 0.00% < 30% | lib/src/api/api_handle_error.dart
- [ ] Error: 2.94% < 30% | lib/src/api/api_request.dart
- [ ] Error: 0.00% < 30% | lib/src/api/json_to.dart
- [ ] Error: 0.00% < 30% | lib/src/auth/auth_result.dart
- [ ] Error: 0.00% < 30% | lib/src/auth/user/app_user_single.dart
- [ ] Error: 0.00% < 30% | lib/src/auth/user/app_user_stacked.dart
- [ ] Error: 0.00% < 30% | lib/src/auth/user_group/app_user_group.dart
- [ ] Error: 0.00% < 30% | lib/src/auth/authenticate.dart
- [ ] Error: 11.11% < 30% | lib/src/datasource/data_set.dart
- [x] Error: 4.76% < 30% | lib/src/auth/user/user_info.dart -> https://github.com/a-givertzman/hmi_networking/pull/46
